### ISSUE TITLE
Tournaments :: Entries :: Issues with new Admin Entry Flow

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#102]
Following updates needed to changes in #77:
- [x] Auto-Approval Summary value is incorrect if not changed as part of flow
    - Will need a `.trigger('change')` method on the approval step to invoke correctly
    - Will need an in-person check added
- [x] When requesting a card payment, the Next button should be hidden until the Pay £xx.xx is pressed and completed
-  [x] A payment authorisation message needs to be added to warn user that once the payment is authorised it will take 7-10 days to be released if an error is made.
- [x] Re-entry/Initial Entries costs appear to be calculated incorrectly again
