### ISSUE TITLE
Tournaments :: Entries :: Association Details

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#45]
Portal Changes:
- [x] Change from BTBA to Association
- [x] Implement Card Image

Admin Changes:
- [x] Implement Association Details as Optional
- [x] Implement View abilities

**Comment by davcpas1234** [comment]
Implemented
