### ISSUE TITLE
Ship List - The English Red Rose Open

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#51]
**Requirements for English Red Rose Open shipped version**

Add/Change
- [x] ~#40, #41, #42 Entry Confirmation Emails~
- [x] ~#28, #45 Entry Functions~
- [x] ~#49 Direct Registration Link~
- [x] ~#44 Lane Draw~ 
- [x] ~#36 Scoresheets~
- [x] ~#53 Squad Status Flow (Overflow, Upcoming, Registration, Check-In, Open/In-Progress, Complete)~
- [x] ~#54 Re-Entry Logic~
- [x] ~#2, #3, #4, #5, #7, #8, #9, #10, #11, #12, #13, #14, #15, #18, #19, #20, #21, #24, #29, #30, #58 Missing Features~ 
- [x] ~#59 QR Codes~
- [x] ~#60 Add Re-entry Only Round Types~
- [x] ~#77 Update Create Entry Flow in Admin Portal~

Bug Fixes
- [x] ~#63 Latency Issues in Live~
- [x] ~#25 Pending Entries not displaying in Squad Grid~
- [x] ~#32 Issue with incorrect finals scoring display~
- [x] ~#33 Issue with incorrect round grid scoring display~
- [x] ~#52 Issues with Squad Grid scoring~
- [x] ~#55, #56 Bonus Calculation issues~

**Comment by davcpas1234** [comment]
This is now due by 30/06
