### ISSUE TITLE
Ship List :: BowlTrack Registration Portal

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#76]
**TODO**
- [x] Check-in
- [x] Check-in Desk Functions
- [x] Check-in Confirmation Emails (Lane Assignment)

**ISSUES**
- [x] #74 Issues with Bootstrap Select on Mobile
- [x] #78 Issue with padding on mobile devices
- [x] #79 Issue with flexbox in IE11

**NON-CRITICAL ISSUES**
- [x] Issue with data consistency - Name formatting example (example: lar** spen** instead of Lar** Spen**)
- [ ] Back portability issue where images are "background" stored but not recreated so caused duplicated submission
