### ISSUE TITLE
Tournaments :: Entries :: Update Create Entry

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#77]
**Tasks:**
~Allow admin to add multiple entries in one flow (Similar to VC-CRV-BT-REG-23594 in Registration Portal)~ Moving to non-urgent flow
- [x] Develop and Test Payments
- [x] Update user flow:
   - When performing a "In-Person" entry - deposits are not required and do not show "On Arrival"
- [x] Check entry is possible before allowing user to proceed. Failure examples are below
   - No "starting" active rounds available
   - No squad spaces available
   - Re-entry only rounds ~(blocked by #60)~
   - Single entry rounds on re-entry
