### ISSUE TITLE
Database :: Insert Routines :: Updates

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#94]
Updates Required:
- [x] `insertNewSquad()`
- [x] `insertNewTeam()` - Team Insert
- [x] `insertNewTeam()` - Players Insert
- [x] `insertNewTeam()` - Team Contact Details Insert
- [x] `insertNewTeamFromPortal()` - Team Insert
- [x] `insertNewTeamFromPortal()` - Players Insert
- [x] `insertNewTeamFromPortal()` - Team Contact Details Insert
- [x] `insertNewDivision()` - Age Based
- [x] `insertNewDivision()` - Average Based
- [x] `insertNewRound()`
- [x] `insertRoundSquadAvailability()`
- [x] `insertRoundLink()`
- [x] `insertNewBonus()`
- [x] `insertNewEntryForExistingTeamInternal()`
- [x] `insertNewEntryForExistingTeam()`
- [x] `insertTournamentEntrySettings()`
- [x] `insertTeamAssignmentsForRoundRobin()`
- [x] `insertPreppedMatches()`

All the above require updates to layout and encryption setups as per latest DB spec (2018.06.02/1829V2)
